
name: RFC
description: Propose a change that improves time/complexity/risk/maintainability or crosses a decision gate
title: "RFC: {{PLACEHOLDER_TITLE}}"
labels: ["type:rfc"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      placeholder: "{{PLACEHOLDER}}"
    validations:
      required: true

  - type: textarea
    id: options
    attributes:
      label: Options (at least 2)
      description: Include baseline and efficiency-first.
      placeholder: |
        Option A (baseline): ...
        Option B (efficiency-first): ...
    validations:
      required: true

  - type: textarea
    id: metrics
    attributes:
      label: Quantified evaluation
      description: Use `METRICS.md` rubric (time, complexity, risk, maintainability, dependencies).
      placeholder: |
        | Option | Human time | Complexity | Regression risk | Maintainability | Dependencies | Notes |
        |---|---|---:|---:|---:|---|---|
        | A |  |  |  |  |  |  |
        | B |  |  |  |  |  |  |
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
      placeholder: "{{PLACEHOLDER}}"
    validations:
      required: true

  - type: textarea
    id: migration
    attributes:
      label: Migration & rollback plan
      placeholder: "{{PLACEHOLDER}}"
    validations:
      required: true

  - type: textarea
    id: verification
    attributes:
      label: Verification / regression plan
      placeholder: "{{PLACEHOLDER}}"
    validations:
      required: true

  - type: dropdown
    id: decision_gate
    attributes:
      label: Decision Gate
      options:
        - "Does not cross a gate"
        - "Crosses a gate (explicit approval required)"
    validations:
      required: true
